### ISSUE TITLE
Handle login failed

### ISSUE THREAD

**Issue by Odonno** [uwp-squad/livecoding-uwp#19]
* [x] Show reconnect (Authenticate) button
* [x] UI that shows login failed

**Comment by andre726** [comment]
c'est lorsque l'on ne souhaite pas se logger et quand même avoir accès au live?

**Comment by Odonno** [comment]
@andre726 J'ai mis à jour la todo list. On ne peut pas avoir accès au stream sans être connecté donc il faut gérer l'application pour se connecter dans tous les cas (tentative de reconnexion si échec par exemple).
